### ISSUE TITLE
net8不支持

### ISSUE THREAD

**Issue by chinasmu** [Roy0309/Img2ColorfulChars#1]
尝试升级到net8，提示System.Drawing不支持，根据提示安装了System.Drawing.Common，
编译之后生成的都是些
;218;235;247m@[38;2;255;255;255m@[38;2;255;255;255m@[38;2;255;255;255m@[38;2;255;255;255m@[38;2;255;255;255m@[38;2;255;255;255m@[38;2;255;255;255m@[38;2;255;255;255m@[38;2;255;255;255m@[38;2;255;255;255m@[38;2;255;255;255m@[38;2;255;255;255m@[38;2;255;255;255m@[38;2;255;255;255m@[38;2;255;255;255m@[38;2;255;255;255m@[38;2;255;255;255m@[38;2;255;255;255m@[38;2;255;255;255m@[38;2;255;255;255m@[38;2;255;255;255m@[38;2;255;255;255m@[38;2;255;255;255m@[38;2;255;255;255m@[38;2;255;255;255m@[38;2;255;255;255m@[38;2;255;255;255m@[38;2;255;255;255m@[38;2;255;255;255m
这种字符，不知道哪里出了问题

**Comment by Roy0309** [comment]
你好，因工作原因，此仓库可能不常更新，欢迎您研究后分享答案，谢谢！
